ALL: contacts flat-file-db-server

contacts: contacts.c
	gcc contacts.c -o contacts

flat-file-db-server: flat-file-db-server.c
	gcc flat-file-db-server.c -o fileserver

clean:
	rm contacts fileserver
